version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  sync-github-with-gitlabci:
    executor:
      name: node/default
    steps:
      - checkout
      - run: # print the name of= the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run: curl https://gitlab.com/api/v4/projects/abdoulayeke12%2Fcv-with-react/mirror/pull?private_token="${private_token}"
      - node/with-cache:
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "00:0a:2c:2d:e7:6d:73:62:e3:ec:fe:47:ef:ac:58:d6"
            - run: echo -e "Host gitlab.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            - run: ls
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    sync-github-with-gitlabci:
      jobs:
        - sync-github-with-gitlabci
